name: Check PR
run-name: Checking PR
on: [pull_request]
jobs:
  check-formating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"
          path: "."

  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create archive
        run: |
          set -x
          APP_VERSION=`grep -i '^version:' rpm/keycloak-httpd-client-install.spec | sed 's/.* //g'`
          echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
          git archive --format=tar.gz --prefix=keycloak-httpd-client-install-$APP_VERSION/ HEAD >keycloak-httpd-client-install-$APP_VERSION.tar.gz
          echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
      - name: Upload tar archive
        uses: actions/upload-artifact@v4
        with:
          name: tar
          path: keycloak-httpd-client-install-*.tar.gz
          retention-days: 30

  build-fedora-rpm:
    runs-on: ubuntu-latest
    container: fedora:latest
    needs: create-archive
    steps:
      - name: Download tar
        uses: actions/download-artifact@v4
        with:
          name: tar
      - name: Build rpm
        run: |
          set -x
          dnf -y install rpm-build python3-devel python3-setuptools
          rpmbuild -D "release_string $GITHUB_SHA" -D "_rpmdir $(pwd)/rpmbuild" -ta keycloak-httpd-client-install-*.tar.gz
          find ./rpmbuild -name '*.rpm' -exec mv {} ./ \;
      - name: Upload rpms
        uses: actions/upload-artifact@v4
        with:
          name: fedora-rpms
          path: "*.rpm"
          retention-days: 30

  build-el-rpm:
    runs-on: ubuntu-latest
    container: rockylinux:9
    needs: create-archive
    steps:
      - name: Download tar
        uses: actions/download-artifact@v4
        with:
          name: tar
      - name: Build rpm
        run: |
          set -x
          dnf -y install rpm-build python3-devel python3-setuptools
          rpmbuild -D "release_string $GITHUB_SHA" -D "_rpmdir $(pwd)/rpmbuild" -ta keycloak-httpd-client-install-*.tar.gz
          find ./rpmbuild -name '*.rpm' -exec mv {} ./ \;
      - name: Upload rpms
        uses: actions/upload-artifact@v4
        with:
          name: el-rpms
          path: "*.rpm"
          retention-days: 30
